/** Finance → Payroll runs (#132): generated, reviewed, approved, exported. */
export const payroll = {
  title: 'Payroll runs',
  intro:
    'One pay period on one pay schedule: generated as a draft, reviewed, approved, then exported for whatever actually pays people. SoftTrack computes no tax and pays nobody.',
  newRun: 'New run',
  loading: 'Loading runs…',
  empty: 'No runs yet. A run is a period on one pay schedule: start with this month.',
  columns: {
    period: 'Period',
    state: 'State',
    totals: 'Totals',
  },
  firstHalf: '{{month}}, 1st half',
  secondHalf: '{{month}}, 2nd half',
  states: {
    draft: 'Draft',
    approved: 'Approved',
    paid: 'Paid',
  },
  missingCount_one: '{{count}} missing',
  missingCount_other: '{{count}} missing',
  showing: 'Showing {{from}}–{{to}} of {{total}}',
  previous: 'Previous',
  next: 'Next',
  /** Generating a run. */
  create: {
    title: 'New payroll run',
    schedule: 'Pay schedule',
    start: 'First day',
    end: 'Last day',
    hint: 'Everybody active paid on this schedule, and everybody with no pay recorded, as a draft to review.',
    submit: 'Generate draft',
    submitting: 'Generating…',
    error: 'Could not generate that run.',
  },
  /** One run. */
  run: {
    back: 'Payroll runs',
    loading: 'Loading the run…',
    notFound: 'That run does not exist, or was a draft that has been thrown away.',
    subtitle: '{{schedule}} · {{range}} · generated by {{name}}, {{date}}',
    steps: 'Where this run is',
    exportCsv: 'Export CSV',
    exporting: 'Exporting…',
    exportFailed: 'Could not export. Try again.',
    exportWaits: 'Approve the run first: the export is what approval makes.',
    approve: 'Approve run',
    markPaid: 'Mark paid',
    markingPaid: 'Marking…',
    deleteDraft: 'Delete draft',
    confirmDelete:
      'Throw this draft away? Its adjustments go with it. Nothing has been approved or paid.',
    missing_one:
      '<strong>{{count}} person has no compensation for this period</strong> and is on the run as missing, not skipped: {{names}}.',
    missing_other:
      '<strong>{{count}} people have no compensation for this period</strong> and are on the run as missing, not skipped: {{names}}.',
    approvedBy:
      'Approved by <strong>{{name}}</strong> on {{date}}. Amounts are copied onto the lines: a raise recorded next week cannot change what this run says was paid.',
    paidBy:
      'Marked paid by <strong>{{name}}</strong> on {{date}}. Approved by {{approver}} on {{approvedOn}}.',
    liveHint:
      'A draft follows compensation as it changes: pay recorded now is on this run until it is approved.',
    columns: {
      person: 'Person',
      department: 'Department',
      compensation: 'Compensation',
      adjustment: 'Adjustment',
      total: 'Line total',
    },
    noDepartment: 'No department',
    noCompensation: 'No compensation recorded',
    recordPay: 'Record pay',
    recordPayFor: 'Record pay for {{name}}',
    addAdjustment: 'Add',
    addAdjustmentFor: 'Add an adjustment for {{name}}',
    editAdjustmentFor: 'Change the adjustment for {{name}}',
    lines_one: '{{count}} line',
    lines_other: '{{count}} lines',
    missingLines_one: '{{count}} missing',
    missingLines_other: '{{count}} missing',
    totalsLabel: 'Totals per currency',
    /** Claims the run pays back (#137), as lines of their own. */
    reimbursement: 'Reimbursement',
    reimbursementClaims_one: 'Reimbursement, {{count}} claim',
    reimbursementClaims_other: 'Reimbursement, {{count}} claims',
    reimbursedTotalsLabel: 'Reimbursements per currency',
    reimbursing: 'Also paying back',
  },
  /** A line's one-off adjustment. */
  adjustment: {
    title: 'Adjust {{name}}’s line',
    amount: 'Amount',
    amountHint:
      'Positive adds to the line, negative takes away. In {{currency}}, the line’s currency.',
    note: 'Why',
    notePlaceholder: 'On-call, 4 weekends',
    save: 'Save adjustment',
    remove: 'Remove adjustment',
    invalid: 'Enter an amount, positive or negative, with at most {{count}} decimal places.',
    error: 'Could not save that adjustment.',
  },
  /** Approving a run. */
  approve: {
    title: 'Approve {{run}}?',
    body: 'Amounts, currencies and departments are copied onto the lines, and the run stops changing. It can then be exported, and later marked paid.',
    missing_one:
      '{{count}} person has no compensation and will not be paid by this run: {{names}}.',
    missing_other:
      '{{count}} people have no compensation and will not be paid by this run: {{names}}.',
    submit: 'Approve run',
    submitting: 'Approving…',
    error: 'Could not approve the run.',
  },
} as const
