"""The custom-statuses migration, against a database with issues in it.

This one moves data rather than just adding tables: every team needs the
default workflow created for it, every issue has to end up in *its own team's*
copy of the column it was in, and the history rows have to become categories.
None of that is autogenerated, and the rest of the suite never runs it -- the
schema there comes from `SQLModel.metadata.create_all`.
"""

import sqlite3

import pytest
from alembic import command
from alembic.config import Config

BEFORE = "816a5f43eb02"
AFTER = "5e8190bb6409"


def _config(db_path) -> Config:
    config = Config("alembic.ini")
    config.set_main_option("script_location", "alembic")
    config.set_main_option("sqlalchemy.url", f"sqlite:///{db_path}")
    return config


@pytest.fixture
def upgraded(tmp_path):
    """Two teams, an issue in every old status, a saved view and some history."""
    db_path = tmp_path / "statuses.db"
    config = _config(db_path)
    command.upgrade(config, BEFORE)

    connection = sqlite3.connect(db_path)
    connection.execute(
        "INSERT INTO user (email, username, hashed_password, full_name,"
        " avatar_color, is_active, is_site_admin, token_version,"
        " email_notifications, created_at) VALUES ('a@b.c','sam','x','Sam',"
        " '#111',1,1,0,1,'2026-01-01')"
    )
    connection.executemany(
        "INSERT INTO team (name, key, next_issue_number, next_cycle_number,"
        " created_at) VALUES (?, ?, 9, 1, '2026-01-01')",
        [("Engineering", "ENG"), ("Design", "DSG")],
    )
    connection.executemany(
        "INSERT INTO issue (team_id, number, title, status, priority, creator_id,"
        " created_at, updated_at) VALUES (?, ?, ?, ?, 'medium', 1, '2026-01-01',"
        " '2026-01-01')",
        [
            (1, 1, "backlog one", "backlog"),
            (1, 2, "todo one", "todo"),
            (1, 3, "started one", "in_progress"),
            (1, 4, "review one", "in_review"),
            (1, 5, "done one", "done"),
            (1, 6, "cancelled one", "cancelled"),
            # The other team's issue must land in the *other team's* Todo.
            (2, 1, "their todo", "todo"),
        ],
    )
    connection.execute(
        "INSERT INTO savedview (team_id, name, owner_id, is_shared, status,"
        " unassigned, created_at, updated_at) VALUES (1,'In review',1,1,"
        " 'in_review',0,'2026-01-01','2026-01-01')"
    )
    connection.execute(
        "INSERT INTO savedview (team_id, name, owner_id, is_shared, unassigned,"
        " created_at, updated_at) VALUES (1,'No status',1,0,0,'2026-01-01',"
        " '2026-01-01')"
    )
    connection.executemany(
        "INSERT INTO issueevent (issue_id, team_id, field, old_value, new_value,"
        " actor_id, created_at) VALUES (1, 1, ?, ?, ?, 1, '2026-01-02')",
        [
            ("status", None, "backlog"),
            ("status", "backlog", "in_progress"),
            ("status", "in_progress", "done"),
            # Not a status row: it must be left exactly as it is.
            ("estimate", None, "5"),
        ],
    )
    connection.commit()
    connection.close()

    command.upgrade(config, AFTER)
    return db_path, config


def _rows(db_path, sql):
    connection = sqlite3.connect(db_path)
    rows = connection.execute(sql).fetchall()
    connection.close()
    return rows


def test_every_team_gets_the_default_workflow(upgraded):
    db_path, _ = upgraded
    assert _rows(
        db_path,
        "SELECT team_id, count(*) FROM workflowstatus GROUP BY team_id ORDER BY team_id",
    ) == [(1, 6), (2, 6)]
    assert _rows(
        db_path,
        "SELECT name, category, position FROM workflowstatus WHERE team_id = 1"
        " ORDER BY position",
    ) == [
        ("Backlog", "backlog", 0),
        ("Todo", "unstarted", 1),
        ("In Progress", "started", 2),
        ("In Review", "started", 3),
        ("Done", "done", 4),
        ("Cancelled", "cancelled", 5),
    ]


def test_every_issue_lands_in_its_own_teams_column(upgraded):
    """The bug this guards: pointing team 2's issue at team 1's Todo would
    take it off its own board and put it on somebody else's."""
    db_path, _ = upgraded
    assert _rows(
        db_path,
        "SELECT i.team_id, i.number, ws.team_id, ws.name FROM issue i"
        " JOIN workflowstatus ws ON ws.id = i.status_id"
        " ORDER BY i.team_id, i.number",
    ) == [
        (1, 1, 1, "Backlog"),
        (1, 2, 1, "Todo"),
        (1, 3, 1, "In Progress"),
        (1, 4, 1, "In Review"),
        (1, 5, 1, "Done"),
        (1, 6, 1, "Cancelled"),
        (2, 1, 2, "Todo"),
    ]


def test_saved_views_keep_their_status_filter(upgraded):
    db_path, _ = upgraded
    assert _rows(
        db_path,
        "SELECT sv.name, ws.name FROM savedview sv"
        " LEFT JOIN workflowstatus ws ON ws.id = sv.status_id ORDER BY sv.id",
    ) == [("In review", "In Review"), ("No status", None)]


def test_history_becomes_categories(upgraded):
    """Lossy on purpose -- see the revision's docstring. `in_progress` and
    `in_review` both become `started`, which is what keeps a chart of the past
    readable after a team rearranges its board."""
    db_path, _ = upgraded
    assert _rows(
        db_path,
        "SELECT field, old_value, new_value FROM issueevent ORDER BY id",
    ) == [
        ("status", None, "backlog"),
        ("status", "backlog", "started"),
        ("status", "started", "done"),
        ("estimate", None, "5"),
    ]


def test_the_old_column_is_gone(upgraded):
    db_path, _ = upgraded
    connection = sqlite3.connect(db_path)
    columns = {row[1] for row in connection.execute("PRAGMA table_info(issue)")}
    connection.close()
    assert "status" not in columns
    assert "status_id" in columns


def test_upgrading_an_empty_database_works(tmp_path):
    config = _config(tmp_path / "empty.db")
    command.upgrade(config, AFTER)
    assert _rows(tmp_path / "empty.db", "SELECT count(*) FROM workflowstatus") == [(0,)]


def test_the_downgrade_puts_the_enum_back(upgraded):
    """Lossy in the other direction too: several columns can mean `started`,
    so an issue that was in review comes back in progress."""
    db_path, config = upgraded
    command.downgrade(config, BEFORE)

    assert _rows(
        db_path, "SELECT number, status FROM issue WHERE team_id = 1 ORDER BY number"
    ) == [
        (1, "backlog"),
        (2, "todo"),
        (3, "in_progress"),
        (4, "in_progress"),
        (5, "done"),
        (6, "cancelled"),
    ]
    connection = sqlite3.connect(db_path)
    tables = {
        row[0]
        for row in connection.execute(
            "SELECT name FROM sqlite_master WHERE type='table'"
        )
    }
    connection.close()
    assert "workflowstatus" not in tables
