"""Where attachment bytes live.

The database holds the metadata; the bytes go somewhere a database is bad at
holding them. That "somewhere" is deliberately behind a two-method seam, so a
self-hoster on one box keeps files on disk and a self-hoster on three boxes
points the same code at object storage without either of them touching
`lib_softtrack/attachments.py`.

Keys are generated by the service (`<shard>/<token><ext>`) and never come from
a request, so path traversal is not reachable from user input. `_check_key`
enforces the shape anyway: a bug in the caller should cost an error, not an
arbitrary file write.
"""

import re
from pathlib import Path
from typing import BinaryIO, Optional, Protocol

#: The exact shape the service mints. Two hex shard characters, a slash, then
#: a hex token with an optional lowercase extension.
_KEY = re.compile(r"^[0-9a-f]{2}/[0-9a-f]{16,64}(\.[a-z0-9]{1,10})?$")


def _check_key(key: str) -> str:
    if not _KEY.fullmatch(key):
        raise ValueError(
            f"Refusing to use a storage key of an unexpected shape: {key!r}"
        )
    return key


class ObjectNotFound(Exception):
    """The metadata row survived but its bytes did not."""


class Storage(Protocol):
    """The whole contract. Anything that can do these three is a backend."""

    def write(self, key: str, data: bytes) -> None: ...

    def open(self, key: str) -> BinaryIO:
        """Return a readable, closeable stream. Raises ObjectNotFound."""
        ...

    def delete(self, key: str) -> None:
        """Remove the object. Deleting one that is already gone is not an error."""
        ...


class LocalStorage:
    """Files under a directory on the local filesystem. The default."""

    def __init__(self, root: Path):
        self.root = Path(root)

    def _path(self, key: str) -> Path:
        return self.root / _check_key(key)

    def write(self, key: str, data: bytes) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        # Write beside the target and rename, so a crash mid-write leaves no
        # half a file that a later read would happily serve as the real one.
        temporary = path.with_name(path.name + ".part")
        temporary.write_bytes(data)
        temporary.replace(path)

    def open(self, key: str) -> BinaryIO:
        try:
            return self._path(key).open("rb")
        except FileNotFoundError as exc:
            raise ObjectNotFound(key) from exc

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)


class S3Storage:
    """Any S3-compatible object store -- AWS S3, MinIO, Ceph, R2, Spaces.

    boto3 is imported here rather than at module scope because it is an
    optional dependency: a self-hoster using the local backend should not have
    to install an AWS SDK to run an issue tracker.

    Credentials are deliberately not settings of this application. boto3's
    default chain (environment, shared config, instance role) already solves
    that problem, and a second copy of it here would be one more place for a
    secret to end up in a config file.
    """

    def __init__(
        self,
        bucket: str,
        *,
        prefix: str = "",
        endpoint_url: str = "",
        region: str = "",
        client=None,
    ):
        self.bucket = bucket
        self.prefix = prefix.strip("/")
        if client is not None:
            self.client = client
        else:
            import boto3  # noqa: PLC0415 -- optional dependency, see docstring

            self.client = boto3.client(
                "s3",
                endpoint_url=endpoint_url or None,
                region_name=region or None,
            )

    def _object_key(self, key: str) -> str:
        checked = _check_key(key)
        return f"{self.prefix}/{checked}" if self.prefix else checked

    def write(self, key: str, data: bytes) -> None:
        self.client.put_object(Bucket=self.bucket, Key=self._object_key(key), Body=data)

    def open(self, key: str) -> BinaryIO:
        try:
            return self.client.get_object(
                Bucket=self.bucket, Key=self._object_key(key)
            )["Body"]
        except Exception as exc:  # botocore raises a generated class
            if type(exc).__name__ in ("NoSuchKey", "ClientError", "404"):
                raise ObjectNotFound(key) from exc
            raise

    def delete(self, key: str) -> None:
        # S3 delete_object is already idempotent: removing an absent key
        # succeeds, which is exactly the contract above.
        self.client.delete_object(Bucket=self.bucket, Key=self._object_key(key))


def build_storage(settings) -> Storage:
    """The backend named by ATTACHMENT_STORAGE."""
    if settings.attachment_storage == "local":
        return LocalStorage(Path(settings.attachment_dir))
    if settings.attachment_storage == "s3":
        return S3Storage(
            settings.attachment_s3_bucket,
            prefix=settings.attachment_s3_prefix,
            endpoint_url=settings.attachment_s3_endpoint_url,
            region=settings.attachment_s3_region,
        )
    raise ValueError(
        f"Unknown ATTACHMENT_STORAGE {settings.attachment_storage!r}. "
        "Supported values are 'local' and 's3'."
    )


_storage: Optional[Storage] = None


def get_storage() -> Storage:
    """FastAPI dependency yielding the configured storage backend.

    A dependency rather than a module-level singleton so tests can override it
    the same way they override the database session, and so the backend is not
    built at import time -- importing this module must not require boto3 or a
    writable directory.
    """
    global _storage
    from web import settings

    if _storage is None:
        _storage = build_storage(settings)
    return _storage


def copy_stream(source: BinaryIO, chunk_size: int = 64 * 1024):
    """Yield an object's bytes, closing it afterwards."""
    try:
        while chunk := source.read(chunk_size):
            yield chunk
    finally:
        close = getattr(source, "close", None)
        if close is not None:
            close()
