"""add external key to issue

Revision ID: 16ea773922cc
Revises: 89e6c2483f7d
Create Date: 2026-09-07 21:45:56.160258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.AutoString()

# revision identifiers, used by Alembic.
revision: str = "16ea773922cc"
down_revision: Union[str, Sequence[str], None] = "89e6c2483f7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Record the identifier an imported issue had in its previous system.

    Nullable: issues created in SoftTrack have no previous key, and that is
    the normal case. Indexed because the importer looks every key up to avoid
    creating the same issue twice on a re-run.
    """
    with op.batch_alter_table("issue", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("external_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_issue_external_key"), ["external_key"], unique=False
        )


def downgrade() -> None:
    """Drop the column, losing the link back to the original tracker."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issue_external_key"))
        batch_op.drop_column("external_key")
