"""add issue links

Revision ID: 55613c0f041c
Revises: e2b56dbe1777
Create Date: 2026-09-07 18:52:41.926648

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.AutoString()

# revision identifiers, used by Alembic.
revision: str = "55613c0f041c"
down_revision: Union[str, Sequence[str], None] = "e2b56dbe1777"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issuelink",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("blocks", "relates_to", "duplicates", name="issuelinktype"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["issue.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["issue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "target_id", "type", name="uq_issue_link"),
    )
    with op.batch_alter_table("issuelink", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_issuelink_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_issuelink_target_id"), ["target_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issuelink", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issuelink_target_id"))
        batch_op.drop_index(batch_op.f("ix_issuelink_source_id"))

    op.drop_table("issuelink")
    # ### end Alembic commands ###
