"""add issue event history

Revision ID: 89e6c2483f7d
Revises: 4522806f02f8
Create Date: 2026-09-07 21:16:37.877642

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.AutoString()

# revision identifiers, used by Alembic.
revision: str = "89e6c2483f7d"
down_revision: Union[str, Sequence[str], None] = "4522806f02f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the issue history table.

    Nothing is backfilled, and nothing can be: this table exists precisely
    because the past cannot be reconstructed from the current rows. Reports
    start being useful from the moment this lands, which is the argument for
    landing it early rather than alongside the charts that consume it.
    """
    op.create_table(
        "issueevent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("issue_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column(
            "field",
            sa.Enum("status", "cycle", "estimate", name="issueeventfield"),
            nullable=False,
        ),
        sa.Column("old_value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("new_value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["user.id"], name="fk_issueevent_actor_id_user"
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"], ["issue.id"], name="fk_issueevent_issue_id_issue"
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["team.id"], name="fk_issueevent_team_id_team"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("issueevent", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_issueevent_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_issueevent_field"), ["field"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_issueevent_issue_id"), ["issue_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_issueevent_team_id"), ["team_id"], unique=False
        )


def downgrade() -> None:
    """Drop the history table, permanently losing every recorded change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issueevent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issueevent_team_id"))
        batch_op.drop_index(batch_op.f("ix_issueevent_issue_id"))
        batch_op.drop_index(batch_op.f("ix_issueevent_field"))
        batch_op.drop_index(batch_op.f("ix_issueevent_created_at"))

    op.drop_table("issueevent")
