"""add user management: usernames, account state, site admins, team invites

Revision ID: b7d3e91a5c04
Revises: 4fabaf161db7
Create Date: 2026-09-08

Hand-written rather than autogenerated. Autogenerate can see the new columns
but not the two things that actually make this migration safe on a database
with rows in it: every existing user needs a username before the column can be
NOT NULL and unique, and an upgraded install needs somebody holding the site
admin flag or nobody can reach the new user directory.
"""

import re
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel  # autogenerate emits sqlmodel.sql.sqltypes.AutoString()

revision: str = "b7d3e91a5c04"
down_revision: Union[str, Sequence[str], None] = "4fabaf161db7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

#: Mirrors USERNAME_PATTERN in lib_identity/usernames.py. Deliberately copied
#: rather than imported: a migration has to keep producing the same result
#: years from now, and importing application code would let a later refactor
#: silently change what this one did.
_MAX_USERNAME = 39
_UNSAFE = re.compile(r"[^a-z0-9._-]+")


def _derive_username(email: str, taken: set[str]) -> str:
    """Turn an address into a free handle, the way the app does for new users."""
    local = email.split("@")[0].lower().strip()
    base = _UNSAFE.sub("-", local).lstrip("._-")[:_MAX_USERNAME] or "user"
    # The handle has to be usable in an @mention, and a single character is
    # too easy to collide with prose.
    if len(base) < 2:
        base = f"{base}-user"

    candidate = base
    suffix = 2
    while candidate in taken:
        tail = str(suffix)
        candidate = f"{base[: _MAX_USERNAME - len(tail)]}{tail}"
        suffix += 1
    taken.add(candidate)
    return candidate


def upgrade() -> None:
    """Add the user columns, backfill them, then create the invite table."""
    # Everything arrives with a server default so the ALTER succeeds on a table
    # that already has rows; `username` arrives nullable because its value has
    # to be computed per row below.
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "is_active", sa.Boolean(), nullable=False, server_default=sa.true()
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_site_admin",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column("token_version", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(sa.Column("last_login_at", sa.DateTime(), nullable=True))

    bind = op.get_bind()
    rows = bind.execute(sa.text('SELECT id, email FROM "user" ORDER BY id')).fetchall()

    taken: set[str] = set()
    for user_id, email in rows:
        bind.execute(
            sa.text('UPDATE "user" SET username = :username WHERE id = :id'),
            {"username": _derive_username(email or "", taken), "id": user_id},
        )

    if rows:
        # The oldest account. On an install being upgraded there is no other
        # signal for who should hold the instance, and leaving it unset would
        # mean nobody could ever reach the admin console to grant it.
        bind.execute(
            sa.text('UPDATE "user" SET is_site_admin = :yes WHERE id = :id'),
            {"yes": True, "id": rows[0][0]},
        )

    # A second batch on purpose: SQLite rebuilds the table from each column's
    # *final* definition, so tightening `username` in the same batch that added
    # it would copy the existing rows into a NOT NULL column before the loop
    # above ever ran. See 4522806f02f8_add_cycles.py for the same trap.
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "username",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        )
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)
        # The defaults were scaffolding for the ALTER; the model has none, and
        # leaving them would make autogenerate report a difference forever.
        batch_op.alter_column(
            "is_active", existing_type=sa.Boolean(), server_default=None
        )
        batch_op.alter_column(
            "is_site_admin", existing_type=sa.Boolean(), server_default=None
        )
        batch_op.alter_column(
            "token_version", existing_type=sa.Integer(), server_default=None
        )

    op.create_table(
        "teaminvite",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # create_type=False: the initial migration already created `teamrole`
        # for teammember.role, and a second CREATE TYPE would abort the
        # upgrade on Postgres. On SQLite this compiles to VARCHAR either way.
        sa.Column(
            "role",
            postgresql.ENUM("admin", "member", name="teamrole", create_type=False),
            nullable=False,
        ),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invited_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"], ["team.id"], name="fk_teaminvite_team_id_team"
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_id"], ["user.id"], name="fk_teaminvite_invited_by_id_user"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "email", name="uq_team_invite_team_email"),
    )
    with op.batch_alter_table("teaminvite", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_teaminvite_team_id"), ["team_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_teaminvite_email"), ["email"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_teaminvite_token"), ["token"], unique=True)


def downgrade() -> None:
    """Drop invites and the user columns, leaving accounts otherwise intact."""
    with op.batch_alter_table("teaminvite", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_teaminvite_token"))
        batch_op.drop_index(batch_op.f("ix_teaminvite_email"))
        batch_op.drop_index(batch_op.f("ix_teaminvite_team_id"))
    op.drop_table("teaminvite")
    # `teamrole` is not dropped: teammember.role still uses it.

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.drop_column("last_login_at")
        batch_op.drop_column("token_version")
        batch_op.drop_column("is_site_admin")
        batch_op.drop_column("is_active")
        batch_op.drop_column("username")
