// @vitest-environment jsdom
/**
 * One payroll run (#132): the missing listed not skipped, adjustments with
 * their reasons, approval that says who it will not pay, and an export that
 * waits for it.
 */
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { cleanup, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

import type { PayrollLineRead, PayrollRunRead } from '@/api/generated/models'
import { financePerson, GRACE } from '@/finance/__tests__/fixtures'
import PayrollRunPage from '@/finance/PayrollRunPage'

const mocks = vi.hoisted(() => ({
  run: undefined as unknown,
  approve: { mutateAsync: vi.fn(), isPending: false },
  paid: { mutateAsync: vi.fn(), isPending: false },
  adjust: { mutateAsync: vi.fn(), isPending: false },
  clear: { mutateAsync: vi.fn(), isPending: false },
  remove: { mutateAsync: vi.fn(), isPending: false },
  download: vi.fn(),
}))

vi.mock('@/api/generated/endpoints/payroll/payroll', async (importOriginal) => ({
  ...(await importOriginal<typeof import('@/api/generated/endpoints/payroll/payroll')>()),
  useGetPayrollRunFinancePayrollRunsRunIdGet: () => ({ isPending: false, data: mocks.run }),
  useApprovePayrollRunFinancePayrollRunsRunIdApprovePost: () => mocks.approve,
  useMarkPayrollRunPaidFinancePayrollRunsRunIdPaidPost: () => mocks.paid,
  useSetPayrollAdjustmentFinancePayrollRunsRunIdLinesUserIdAdjustmentPut: () => mocks.adjust,
  useClearPayrollAdjustmentFinancePayrollRunsRunIdLinesUserIdAdjustmentDelete: () => mocks.clear,
  useDeletePayrollRunFinancePayrollRunsRunIdDelete: () => mocks.remove,
}))

vi.mock('@/api/generated/endpoints/currencies/currencies', async (importOriginal) => ({
  ...(await importOriginal<typeof import('@/api/generated/endpoints/currencies/currencies')>()),
  useListCurrenciesCurrenciesGet: () => ({
    data: [
      { code: 'GBP', minor_units: 2 },
      { code: 'USD', minor_units: 2 },
    ],
  }),
}))

vi.mock('@/finance/download', () => ({ downloadExport: mocks.download }))

function line(id: number, name: string, overrides: Partial<PayrollLineRead> = {}): PayrollLineRead {
  return {
    person: financePerson(id, name),
    department: { id: 1, name: 'Engineering' },
    compensation_id: id * 10,
    amount_minor: 645000,
    currency: 'GBP',
    total_minor: 645000,
    adjustment_minor: 0,
    adjustment_note: null,
    missing: false,
    ...overrides,
  }
}

const MISSING = {
  compensation_id: null,
  amount_minor: null,
  currency: null,
  total_minor: null,
  missing: true,
}

function draft(overrides: Partial<PayrollRunRead> = {}): PayrollRunRead {
  return {
    id: 7,
    pay_schedule: 'monthly',
    period_start: '2026-09-01',
    period_end: '2026-09-30',
    state: 'draft',
    created_by: GRACE,
    created_at: '2026-09-26T10:00:00',
    approved_by: null,
    approved_at: null,
    paid_by: null,
    paid_at: null,
    totals: [
      { currency: 'GBP', amount_minor: 645000, lines: 1 },
      { currency: 'USD', amount_minor: 835000, lines: 1 },
    ],
    line_count: 4,
    missing_count: 2,
    lines: [
      line(1, 'Amina Khan'),
      line(2, 'Daniel Okafor', {
        amount_minor: 795000,
        currency: 'USD',
        adjustment_minor: 40000,
        adjustment_note: 'On-call, 4 weekends',
        total_minor: 835000,
      }),
      line(3, 'Ben Adeyemi', { ...MISSING, department: null }),
      line(4, 'Elena Petrova', MISSING),
    ],
    ...overrides,
  }
}

function renderRun(run: PayrollRunRead) {
  mocks.run = run
  render(
    <QueryClientProvider client={new QueryClient()}>
      <MemoryRouter initialEntries={['/settings/finance/payroll/7']}>
        <Routes>
          <Route path="/settings/finance/payroll/:runId" element={<PayrollRunPage />} />
        </Routes>
      </MemoryRouter>
    </QueryClientProvider>,
  )
  return userEvent.setup()
}

beforeEach(() => {
  for (const mutation of [mocks.approve, mocks.paid, mocks.adjust, mocks.clear, mocks.remove]) {
    mutation.mutateAsync.mockReset().mockResolvedValue({})
  }
  mocks.download.mockReset().mockResolvedValue(undefined)
})

afterEach(() => {
  cleanup()
})

describe('A draft run', () => {
  it('says what it is, and who has no compensation, by name', () => {
    renderRun(draft())
    expect(screen.getByRole('heading', { name: 'September 2026' })).toBeTruthy()
    expect(
      screen.getByText(
        'Monthly · 1 Sep 2026 – 30 Sep 2026 · generated by Grace Mensah, 26 Sep 2026',
      ),
    ).toBeTruthy()
    expect(screen.getByRole('list', { name: 'Where this run is' }).textContent).toMatch(
      '1Draft2Approved3Paid',
    )
    expect(screen.getByText(/have no compensation for this period/).closest('p')?.textContent).toBe(
      '2 people have no compensation for this period and are on the run as missing, not skipped: Ben Adeyemi and Elena Petrova.',
    )
  })

  it('shows each line, its adjustment and its total, and the missing ones last', () => {
    renderRun(draft())
    const rows = screen.getAllByRole('row').slice(1)
    expect(rows.map((row) => within(row).getAllByRole('cell')[0].textContent)).toEqual([
      'AKAmina Khan',
      'DODaniel Okafor',
      'BABen Adeyemi',
      'EPElena Petrova',
    ])
    expect(rows[1].textContent).toMatch('$7,950.00+$400.00On-call, 4 weekends$8,350.00')
    expect(within(rows[2]).getByText('No compensation recorded')).toBeTruthy()
    expect(within(rows[2]).getByText('No department')).toBeTruthy()
    expect(screen.getByText(/^2 lines/).textContent).toBe('2 lines · 2 missing')
  })

  it('does not export until it is approved', () => {
    renderRun(draft())
    const exportButton = screen.getByRole('button', { name: 'Export CSV' }) as HTMLButtonElement
    expect(exportButton.disabled).toBe(true)
    expect(exportButton.title).toBe('Approve the run first: the export is what approval makes.')
  })

  it('approves after saying who it will not pay', async () => {
    const user = renderRun(draft())
    await user.click(screen.getByRole('button', { name: 'Approve run' }))
    const dialog = screen.getByRole('dialog', { name: 'Approve September 2026?' })
    expect(dialog.textContent).toMatch(
      '2 people have no compensation and will not be paid by this run: Ben Adeyemi and Elena Petrova.',
    )
    await user.click(within(dialog).getByRole('button', { name: 'Approve run' }))
    expect(mocks.approve.mutateAsync).toHaveBeenCalledWith({ runId: 7 })
  })

  it('takes an adjustment with a sign and a reason', async () => {
    const user = renderRun(draft())
    await user.click(screen.getByRole('button', { name: 'Add an adjustment for Amina Khan' }))
    const dialog = screen.getByRole('dialog', { name: 'Adjust Amina Khan’s line' })
    const save = within(dialog).getByRole('button', {
      name: 'Save adjustment',
    }) as HTMLButtonElement

    await user.type(within(dialog).getByLabelText('Amount'), '-950.50')
    expect(save.disabled).toBe(true) // No reason yet.
    await user.type(within(dialog).getByLabelText('Why'), 'Unpaid leave, 2 days')
    await user.click(save)

    expect(mocks.adjust.mutateAsync).toHaveBeenCalledWith({
      runId: 7,
      userId: 1,
      data: { amount_minor: -95050, note: 'Unpaid leave, 2 days' },
    })
  })

  it('opens an existing adjustment to change or remove it', async () => {
    const user = renderRun(draft())
    await user.click(
      screen.getByRole('button', { name: 'Change the adjustment for Daniel Okafor' }),
    )
    const dialog = screen.getByRole('dialog')
    expect((within(dialog).getByLabelText('Amount') as HTMLInputElement).value).toBe('400.00')
    await user.click(within(dialog).getByRole('button', { name: 'Remove adjustment' }))
    expect(mocks.clear.mutateAsync).toHaveBeenCalledWith({ runId: 7, userId: 2 })
  })

  it('records pay for somebody missing from the line itself', async () => {
    const user = renderRun(draft())
    await user.click(screen.getByRole('button', { name: 'Record pay for Ben Adeyemi' }))
    expect(screen.getByRole('dialog', { name: 'Record pay for Ben Adeyemi' })).toBeTruthy()
  })
})

describe('An approved run', () => {
  const approved = () =>
    draft({
      state: 'approved',
      approved_by: GRACE,
      approved_at: '2026-09-28T09:00:00',
    })

  it('says who approved it, and offers nothing that would change it', () => {
    renderRun(approved())
    expect(screen.getByText(/Approved by/).textContent).toBe(
      'Approved by Grace Mensah on 28 Sep 2026. Amounts are copied onto the lines: a raise recorded next week cannot change what this run says was paid.',
    )
    expect(screen.queryByRole('button', { name: 'Approve run' })).toBeNull()
    expect(screen.queryByRole('button', { name: /Add an adjustment/ })).toBeNull()
    expect(screen.queryByRole('button', { name: /Record pay/ })).toBeNull()
    expect(screen.queryByRole('button', { name: 'Delete draft' })).toBeNull()
  })

  it('exports, and is marked paid', async () => {
    const user = renderRun(approved())
    await user.click(screen.getByRole('button', { name: 'Export CSV' }))
    expect(mocks.download).toHaveBeenCalledWith(
      '/finance/payroll/runs/7/export',
      'payroll-2026-09-01.csv',
    )
    await user.click(screen.getByRole('button', { name: 'Mark paid' }))
    expect(mocks.paid.mutateAsync).toHaveBeenCalledWith({ runId: 7 })
  })
})
